from __future__ import annotations
"""
campaigns.py — Agent 2: The Campaign Manager

This module handles the lifecycle of an outreach campaign:
1. Loading lists from the Prospector results folder.
2. Generating draft emails for everyone on the list (via outreach_ai).
3. Saving and updating the campaign state inside `backend/campaigns/`.
"""

import os
import uuid
import random
import pandas as pd
import json
from datetime import datetime
import glob

from agents.outreach_ai import generate_cold_email, score_leads
from agents.outreach_sender import send_gmail_human_like, send_whatsapp_human_like, MAX_DAILY_EMAIL, MAX_DAILY_WHATSAPP
from agents.db import get_contact_info, record_contact

import asyncio
from datetime import datetime, timedelta

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
CAMPAIGNS_DIR = os.path.join(os.path.dirname(__file__), "..", "campaigns")
SPINTAX_ASUNTOS_PATH = os.path.join(os.path.dirname(__file__), "..", "spintax_asuntos.txt")

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(CAMPAIGNS_DIR, exist_ok=True)

def _load_spintax_subjects() -> list[str]:
    """Loads subject line variants from spintax_asuntos.txt. Returns shuffled list."""
    try:
        with open(SPINTAX_ASUNTOS_PATH, 'r', encoding='utf-8') as f:
            subjects = [line.strip() for line in f if line.strip()]
        if subjects:
            random.shuffle(subjects)
            return subjects
    except Exception:
        pass
    return ["Pregunta rápida", "Una canción que quería compartir", "Algo que acabo de lanzar"]

def _get_rotating_subject(idx: int, spintax_pool: list[str], csv_subject: str = "") -> str:
    """Returns the best subject: CSV value if present, else rotates through spintax pool."""
    if csv_subject and csv_subject.strip():
        return csv_subject.strip()
    if spintax_pool:
        return spintax_pool[idx % len(spintax_pool)]
    return "Pregunta rápida"

def list_scraped_csvs() -> list[dict]:
    """Returns a list of all CSVs generated by Agent 1."""
    files = glob.glob(os.path.join(RESULTS_DIR, "*.csv"))
    # Sort newest first
    files.sort(key=os.path.getctime, reverse=True)
    
    results = []
    for f in files:
        filename = os.path.basename(f)
        try:
            # OPTIMIZATION: Use lightweight line counting instead of Pandas
            # This is 10x faster and uses nearly zero memory.
            with open(f, 'r', encoding='utf-8-sig') as csv_file:
                # Count lines and find if 'email' header exists without parsing whole thing
                first_line = csv_file.readline()
                has_email = "email" in first_line.lower()
                
                # Count remaining lines
                total_leads = sum(1 for line in csv_file)
                
            results.append({
                "filename": filename,
                "total_leads": total_leads,
                "contactable": total_leads if has_email else 0, # Approximation for UI speed
                "created_at": os.path.getctime(f)
            })
        except Exception as e:
            print(f"⚠️ Error reading list {filename}: {str(e)}")
            pass
    return results

def get_campaign(campaign_id: str) -> dict:
    c_path = os.path.join(CAMPAIGNS_DIR, f"{campaign_id}.json")
    if not os.path.exists(c_path):
        return None
    with open(c_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_campaign(campaign: dict):
    """Saves campaign state with a basic retry mechanism to handle file locks."""
    import time
    c_path = os.path.join(CAMPAIGNS_DIR, f"{campaign['id']}.json")
    for attempt in range(5):
        try:
            with open(c_path, 'w', encoding='utf-8') as f:
                json.dump(campaign, f, indent=4)
            return
        except IOError:
            time.sleep(0.05) # Wait 50ms and try again
    # Final attempt without catching to raise error if still failing
    with open(c_path, 'w', encoding='utf-8') as f:
        json.dump(campaign, f, indent=4)

def list_campaigns() -> list[dict]:
    """Returns a summary of all existing campaigns."""
    files = glob.glob(os.path.join(CAMPAIGNS_DIR, "*.json"))
    results = []
    for f in files:
        try:
            with open(f, 'r', encoding='utf-8') as jf:
                camp = json.load(jf)
                # Return a summary to keep list light
                results.append({
                    "id": camp["id"],
                    "csv_source": camp.get("csv_source", ""),
                    "status": camp["status"],
                    "created_at": camp["created_at"],
                    "stats": camp.get("stats", {"sent": 0, "failed": 0, "pending": 0})
                })
        except Exception:
            pass
    # Sort newest first
    results.sort(key=lambda x: x["created_at"], reverse=True)
    return results

async def draft_campaign(csv_filename: str, pitch: str, sender_name: str = "", context_files: list = None, log_callback=None) -> dict:
    """
    Creates a new campaign, loads the CSV, filters for contactable leads, 
    and iterates them to draft personalized emails. 
    """
    if log_callback:
        await log_callback("📂 Loading contactable leads from CSV...")
        
    csv_path = os.path.join(RESULTS_DIR, csv_filename)
    df = pd.read_csv(csv_path)
    
    # Filter only leads that have an explicit email
    df = df[df['email'].notna() & (df['email'] != '')]
    # Fill any NaN to avoid invalid JSON NaN tokens
    df = df.fillna("")
    raw_leads = df.to_dict('records')
    
    # 1. Filter out recently contacted leads and annotate touch count
    leads = []
    for lead in raw_leads:
        info = get_contact_info(lead.get('email'))
        if info:
            lead['touch_count'] = info.get('touch_count', 0)
            if info.get('last_contacted_at'):
                last_contact = datetime.fromisoformat(info['last_contacted_at'])
                if datetime.now() - last_contact < timedelta(days=7):
                    # Skip if contacted in the last 7 days
                    continue
        else:
            lead['touch_count'] = 0
        leads.append(lead)
    
    if not leads:
        if log_callback:
            await log_callback("❌ No new actionable emails found in this CSV. Cannot deploy campaign.")
        return {"status": "failed"}

    # 2. Score leads — skip for large batches to avoid WebSocket timeout
    if len(leads) <= 100:
        if log_callback:
            await log_callback(f"🧠 AI is scoring {len(leads)} leads to determine best channels...")
        lead_scores = await score_leads(leads, pitch, context_files=context_files, log_callback=log_callback)
        for lead in leads:
            lead['ai_score'] = lead_scores.get(lead['email'], 50)
        leads.sort(key=lambda x: x['ai_score'], reverse=True)
    else:
        if log_callback:
            await log_callback(f"⚡ Large batch ({len(leads)} leads): Skipping scoring to maximize speed. All leads set to score 75.")
        for lead in leads:
            lead['ai_score'] = 75
    
    campaign_id = str(uuid.uuid4())
    campaign = {
        "id": campaign_id,
        "csv_source": csv_filename,
        "pitch": pitch,
        "context_files": context_files or [],
        "status": "drafting",
        "created_at": datetime.now().isoformat(),
        # Virtual SDR Settings (Defaults)
        "settings": {
            "daily_email_limit": 10,
            "daily_whatsapp_limit": 5,
            "channel_priority": "hybrid",
            "send_window": {"start": 9, "end": 17},
            "delay_style": "standard",
            "hours_window": 6,
            "volume_jitter": True,
            "time_jitter": True,
            "signature_jitter": True,
            "sender_name": sender_name
        },
        "stats": {
            "sent": 0,
            "failed": 0,
            "pending": 0
        },
        "leads": []
    }
    
    # Build skeleton
    spintax_pool = _load_spintax_subjects()  # Shuffled pool — rotates per lead
    for idx, lead in enumerate(leads):
        pref_channel = "whatsapp_and_email" if idx < campaign["settings"]["daily_whatsapp_limit"] else "email_only"
        
        # Subject: use CSV value if available, else rotate from spintax pool
        spintax_subject = _get_rotating_subject(idx, spintax_pool, lead.get('asunto_email', ''))
        
        campaign["leads"].append({
            "name": lead.get('name', ''),
            "email": lead.get('email', ''),
            "phone": lead.get('phone', ''),
            "category": lead.get('category', ''),
            "website": lead.get('website', ''),
            "ai_notes": lead.get('ai_notes', ''),
            "ai_score": lead.get('ai_score', 50),
            "touch_count": lead.get('touch_count', 0),
            "preferred_channel": pref_channel,
            "status": "pending_approval",
            "draft_subject": "",
            "draft_body": "",
            # Subject rotated from spintax pool (or taken from CSV if asunto_email column exists)
            "spintax_subject": spintax_subject
        })
        
    save_campaign(campaign)
    
    # Generate drafts
    total = len(campaign["leads"])
    for idx, lead_entry in enumerate(campaign["leads"]):
        if log_callback:
            await log_callback(f"✍️ Drafting {idx+1}/{total}: Customizing email for {lead_entry['name']}...")
            
        try:
            draft = await generate_cold_email(lead_entry, pitch, context_files=context_files, log_callback=None)
            # SUBJECT: Always from spintax rotation — never from the AI.
            # AI only writes the body for personalization.
            lead_entry["draft_subject"] = lead_entry.get('spintax_subject') or 'Pregunta rápida'
            lead_entry["draft_body"] = draft.get("body", "Hi, I'd like to connect.")
            # Save progress iteratively
            save_campaign(campaign)
            
            # Throttle to 1.5s — with 8 keys rotating, effective rate is well within free tier limits
            await asyncio.sleep(1.5)
        except Exception as e:
            if log_callback:
                await log_callback(f"⚠️ Error drafting for {lead_entry['name']}: {str(e)}. AI offline — body will use pitch template.")
            lead_entry["draft_subject"] = lead_entry.get('spintax_subject', '') or 'Pregunta rápida'
            lead_entry["draft_body"] = pitch  # fallback: use raw pitch as body
            lead_entry["status"] = "draft_failed"
            
    campaign["status"] = "drafted"
    campaign["stats"]["pending"] = len([l for l in campaign["leads"] if l["status"] == "pending_approval"])
    save_campaign(campaign)
    
    if log_callback:
        await log_callback("✅ All drafts complete! Ready for Review Queue.")
        
    return campaign

async def run_campaign_loop(campaign_id: str, log_callback=None):
    """
    Main background loop for a campaign. 
    Implements Layer 3: Drip Scheduling.
    """
    campaign = get_campaign(campaign_id)
    if not campaign or campaign["status"] != "active":
        return

    # Create a wrapper for logging that persists to the campaign object
    async def persistent_log(msg: str):
        # Always get fresh state before logging to avoid overwriting recent changes
        curr_camp = get_campaign(campaign_id) or campaign
        print(f"[{campaign_id}] {msg}")
        curr_camp["logs"] = curr_camp.get("logs", [])
        # Add timestamp to log
        timestamp = datetime.now().strftime("%H:%M:%S")
        formatted_log = f"[{timestamp}] {msg}"
        curr_camp["logs"].append(formatted_log)
        # Keep only last 100 logs for performance
        if len(curr_camp["logs"]) > 100:
            curr_camp["logs"] = curr_camp["logs"][-100:]
        save_campaign(curr_camp)
        if log_callback:
            await log_callback(formatted_log)

    await persistent_log("🧠 Neural Engine Initialized. Analyzing delivery patterns...")

    leads_to_send = [l for l in campaign["leads"] if l["status"] == "pending_approval"]
    
    # Layer 1 Enforcement: Daily Caps
    email_limit = min(campaign["settings"].get("daily_email_limit", 30), MAX_DAILY_EMAIL)
    whatsapp_limit = min(campaign["settings"].get("daily_whatsapp_limit", 10), MAX_DAILY_WHATSAPP)
    block_cross = campaign["settings"].get("block_cross_channel_same_day", True)
    
    if campaign["settings"].get("volume_jitter", False):
        email_limit = random.randint(int(email_limit * 0.8), email_limit)
        whatsapp_limit = random.randint(int(whatsapp_limit * 0.8), whatsapp_limit)

    if not leads_to_send:
        await persistent_log("🏁 No more pending leads for this campaign.")
        campaign["status"] = "completed"
        save_campaign(campaign)
        return

    await persistent_log(f"🚀 Starting Virtual SDR session (Targets: {email_limit} emails, {whatsapp_limit} WA).")

    emails_sent_today = 0
    whatsapps_sent_today = 0
    consecutive_failures = 0
    
    # Import delay presets to calculate gaps
    from .outreach_sender import DELAY_PRESETS
    
    try:
        for i, lead in enumerate(leads_to_send):
            if emails_sent_today >= email_limit and whatsapps_sent_today >= whatsapp_limit:
                await persistent_log("🏁 Daily caps reached for all active channels.")
                break

            # Refresh campaign state in case it was paused/stopped
            campaign = get_campaign(campaign_id)
            if campaign["status"] != "active":
                await persistent_log("⏸️ Campaign paused or stopped. Exiting runner.")
                return

            # Check Send Window
            send_window = campaign["settings"].get("send_window", {"start": 9, "end": 17})
            current_hour = datetime.now().hour
            
            if send_window["start"] < send_window["end"]:
                in_window = send_window["start"] <= current_hour < send_window["end"]
            else:
                in_window = current_hour >= send_window["start"] or current_hour < send_window["end"]
                
            if not in_window:
                campaign = get_campaign(campaign_id)
                campaign["status"] = "paused"
                save_campaign(campaign)
                await persistent_log(f"🌙 Outside Active Send Window ({send_window['start']}:00 - {send_window['end']}:00). Pausing campaign until window opens.")
                return

            # ━━ PRE-SEND: Register Digital Twin ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            from .db import db_conn
            import uuid
            
            with db_conn() as conn:
                cursor = conn.cursor()
                cursor.execute("INSERT OR IGNORE INTO campaigns (id, csv_source, pitch, created_at, status) VALUES (?, ?, ?, ?, ?)",
                               (campaign_id, campaign.get('csv_source', ''), campaign.get('pitch', ''), campaign.get('created_at', ''), 'active'))
                
                cursor.execute("SELECT id FROM contacts WHERE email = ?", (lead.get('email', ''),))
                contact_row = cursor.fetchone()
                contact_id = contact_row['id'] if contact_row else None
                
                if not contact_id:
                    cursor.execute("INSERT INTO contacts (email, name, phone) VALUES (?, ?, ?)", (lead.get('email', ''), lead.get('name', ''), lead.get('phone', '')))
                    contact_id = cursor.lastrowid
                
                conv_id = f"conv_{uuid.uuid4().hex[:12]}"
                cursor.execute("INSERT INTO conversations (id, lead_id, campaign_id, channel, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                               (conv_id, contact_id, campaign_id, 'email', datetime.now().isoformat(), datetime.now().isoformat()))
                
                outbound_id = f"out_{uuid.uuid4().hex[:12]}"
                cursor.execute('''
                    INSERT INTO outbound_messages (id, conversation_id, contact_id, campaign_id, channel, subject, body, status, sent_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (outbound_id, conv_id, contact_id, campaign_id, 'email', lead.get('draft_email_subject') or lead.get('draft_subject', ''), lead.get('draft_email_body') or lead.get('draft_body', ''), 'pending', datetime.now().isoformat()))
                
                cursor.execute('UPDATE contacts SET touch_count = COALESCE(touch_count, 0) + 1 WHERE id = ?', (contact_id,))
                conn.commit()

            # Execute Send
            channel_priority = campaign["settings"].get("channel_priority", "hybrid")
            # If the importer didn't set preferred_channel, we fallback to hybrid
            pref_channel = lead.get("preferred_channel", "whatsapp_and_email")
            
            success_whatsapp = False
            success_email = False
            outbound_meta = {"success": False, "message_id": None}
            
            await persistent_log(f"🎯 Target: {lead.get('name', 'Unknown')} ({lead.get('email', '')})")

            body_wa = lead.get("draft_whatsapp_body") or lead.get("draft_body", "")
            body_em = lead.get("draft_email_body") or lead.get("draft_body", "")

            if whatsapps_sent_today < whatsapp_limit and channel_priority in ["hybrid", "whatsapp_only"] and pref_channel == "whatsapp_and_email":
                if lead.get("phone") and body_wa:
                    success_whatsapp = await send_whatsapp_human_like(
                        to_phone=lead["phone"],
                        body=body_wa,
                        delay_style=campaign["settings"]["delay_style"],
                        time_jitter=campaign["settings"].get("time_jitter", False),
                        signature_jitter=campaign["settings"].get("signature_jitter", False),
                        log_callback=persistent_log
                    )
                    if success_whatsapp:
                        whatsapps_sent_today += 1
                elif channel_priority == "whatsapp_only":
                    await persistent_log(f"⚠️ Skipped {lead.get('name', '')}: No phone number or WhatsApp body")

            skip_email = False
            if success_whatsapp and block_cross:
                skip_email = True
                await persistent_log(f"🛡️ Blocked cross-channel: WhatsApp already sent today.")

            if not skip_email and emails_sent_today < email_limit and (channel_priority in ["hybrid", "email_only"] or (not success_whatsapp and channel_priority == "hybrid")):
                if lead.get("email") and body_em:
                    outbound_meta = await send_gmail_human_like(
                        to_email=lead["email"],
                        subject=lead.get("draft_email_subject") or lead.get("draft_subject", "Pregunta"),
                        body=body_em,
                        delay_style=campaign["settings"]["delay_style"],
                        time_jitter=campaign["settings"].get("time_jitter", False),
                        signature_jitter=campaign["settings"].get("signature_jitter", False),
                        sender_name=campaign["settings"].get("sender_name", ""),
                        log_callback=persistent_log
                    )
                    success_email = outbound_meta["success"]
                    if success_email:
                        emails_sent_today += 1

            success = success_whatsapp or success_email
            
            # ━━ POST-SEND: Update Identifiers ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with db_conn() as conn:
                cursor = conn.cursor()
                cursor.execute('''
                    UPDATE outbound_messages 
                    SET rfc_message_id = ?, status = ?, sent_at = ?
                    WHERE id = ?
                ''', (outbound_meta.get("message_id"), 'sent' if success else 'failed', datetime.now().isoformat(), outbound_id))
                
                cursor.execute("UPDATE conversations SET updated_at = ?, state = ? WHERE id = ?",
                               (datetime.now().isoformat(), 'outbound_sent' if success else 'failed', conv_id))
                conn.commit()

            if not success:
                consecutive_failures += 1
                if consecutive_failures >= 3:
                    campaign = get_campaign(campaign_id)
                    campaign["status"] = "paused"
                    save_campaign(campaign)
                    await persistent_log("🛑 Reputation Guard: 3 consecutive failures detected. Pausing campaign to protect domain.")
                    return
            else:
                consecutive_failures = 0
                record_contact(lead["email"], lead.get("phone", ""), lead["name"])

            # Update Lead & Campaign State (Legacy JSON fallback for UI)
            for l in campaign["leads"]:
                if l["email"] == lead["email"]:
                    l["status"] = "sent" if success else "failed"
                    l["sent_at"] = datetime.now().isoformat()
                    # Add trace ID for easier cross-referencing
                    l["rfc_message_id"] = outbound_meta.get("message_id")
            
            campaign["stats"]["sent"] = len([l for l in campaign["leads"] if l["status"] == "sent"])
            campaign["stats"]["failed"] = len([l for l in campaign["leads"] if l["status"] == "failed"])
            campaign["stats"]["pending"] = len([l for l in campaign["leads"] if l["status"] == "pending_approval"])
            
            save_campaign(campaign)
            
            # ━━ INTERVAL DELAY (Post-send) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            if success and i < len(leads_to_send) - 1:
                delay_style = campaign["settings"].get("delay_style", "standard")
                min_delay, max_delay = DELAY_PRESETS.get(delay_style.lower(), DELAY_PRESETS["standard"])
                delay_seconds = random.uniform(min_delay, max_delay)
                
                if campaign["settings"].get("time_jitter", False):
                    salt = random.uniform(0.85, 1.15)
                    delay_seconds = delay_seconds * salt
                
                minutes_wait = round(delay_seconds / 60, 1)
                await persistent_log(f"⏳ Mimicking human behavior... Waiting {minutes_wait} minutes before next send.")
                await asyncio.sleep(delay_seconds)

    except Exception as loop_error:
        import traceback
        campaign = get_campaign(campaign_id)
        campaign["status"] = "error"
        save_campaign(campaign)
        await persistent_log(f"💥 Critical Runner Error: {str(loop_error)}\n{traceback.format_exc()}")
        return

    if log_callback:
        await log_callback(f"✅ Daily session complete. Sent {len(to_send_today)} emails.")
