from __future__ import annotations
"""
extractor.py — Google Maps Playwright Scraper (Agent 1: The Prospector)

Accepts a LIST of queries (generated by ai_brain.generate_queries), scrapes Google Maps
for each one using stealth Playwright, and extracts lead details.
Uses a fast CSS selector for phone numbers, with AI as a fallback.
Deduplicates across queries so the same business is never scraped twice.
"""

import asyncio
from typing import Optional
from playwright.async_api import async_playwright
from playwright_stealth import Stealth
from agents.config import SCRAPE_DELAY_SECONDS
from agents.db import is_already_known
import re

SCRAPE_DELAY_SECONDS = 0.5
RESTART_EVERY = 1000

# Blacklist to filter out garbage or out-of-target leads returned by Google Maps
NAME_BLACKLIST = [
    "mercadona", "carrefour", "lidl", "aldi", "dia ", "supermercado", "hipermercado",
    "fisioterapia", "fisio ", "podología", "podologo", "veterinari", "farmacia"
]

def _generate_dedupe_keys(lead: dict) -> list[str]:
    """Generates a hierarchical list of unique keys for a lead to prevent duplicates."""
    keys = []
    
    # 1. Maps URL (CID or exact place)
    map_url = lead.get('map_url', '')
    if map_url:
        clean_url = map_url.split('/data=')[0].split('?')[0].strip()
        keys.append(f"url:{clean_url}")
        
    # 2. Phone
    phone = lead.get('phone', '')
    if phone:
        clean_phone = re.sub(r'\D', '', phone)
        if len(clean_phone) >= 9:
            keys.append(f"phone:{clean_phone}")
            
    # 3. Website
    website = lead.get('website', '')
    if website:
        domain = website.replace('https://', '').replace('http://', '').replace('www.', '').split('/')[0].lower()
        # Ignore generic social/parent domains so franchises don't overwrite each other
        generic_domains = {"instagram.com", "facebook.com", "linktr.ee", "twitter.com", "tiktok.com", "youtube.com", "linkedin.com", "sanitas.es", "vitaldent.com", "adeslasdental.es", "vivantadental.es", "clinicabaviera.com", "dentix.com"}
        if domain and domain not in generic_domains:
            keys.append(f"web:{domain}")
            
    # 4 & 5. Name + Location Fallback
    name = str(lead.get('name', '')).strip().lower()
    address = str(lead.get('address', '')).strip().lower()
    if name:
        if address:
            keys.append(f"name+addr:{name}|{address}")
            city = address.split(',')[-1].strip()
            keys.append(f"name+city:{name}|{city}")
        else:
            keys.append(f"name:{name}") # Extreme fallback
            
    return keys


async def _dismiss_cookie_banner(page) -> None:
    """Try to dismiss the Google consent/cookie popup (common in EU)."""
    # Wait for the page to at least start loading something
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=3000)
    except:
        pass

    # Combined selector for faster matching across different regions
    combined_selector = (
        'button:has-text("Accept all"), '
        'button:has-text("Aceptar todo"), '
        'button:has-text("Alle akzeptieren"), '
        'button:has-text("Tout accepter"), '
        'form[action*="consent"] button, '
        'button[aria-label*="Accept"]'
    )
    
    try:
        # Use a single wait for any of the buttons to appear
        btn = await page.wait_for_selector(combined_selector, timeout=3000)
        if btn:
            await btn.click()
            await asyncio.sleep(1) # Short wait for transition
            return
    except Exception:
        pass
async def _extract_place_details(page, link: str) -> Optional[dict]:
    """Visit a single Google Maps place URL and extract all available details."""
    try:
        await page.goto(link, timeout=15000, wait_until="commit")
        await asyncio.sleep(SCRAPE_DELAY_SECONDS)

        # Business name
        try:
            name = await page.locator('h1').first.inner_text(timeout=4000)
        except Exception:
            name = "Unknown"
            
        # Check blacklist early to avoid unnecessary processing
        name_lower = name.lower()
        if any(bad_word in name_lower for bad_word in NAME_BLACKLIST):
            return None

        # Category
        try:
            category = await page.locator('button.DkEaL').first.inner_text(timeout=2000)
        except Exception:
            category = ""

        # Website — try both selectors in parallel
        website = ""
        try:
            web_link = await page.locator('a[data-item-id="authority"]').get_attribute('href', timeout=2000)
            if web_link:
                website = web_link
        except Exception:
            pass
        if not website:
            try:
                web_link = await page.locator('a[aria-label*="Website"]').get_attribute('href', timeout=2000)
                if web_link:
                    website = web_link
            except Exception:
                pass

        # Phone — primary method via data-item-id (most reliable)
        phone = ""
        try:
            phone_button = page.locator('button[data-item-id^="phone:"]')
            if await phone_button.count() > 0:
                data_id = await phone_button.first.get_attribute('data-item-id', timeout=2000)
                if data_id:
                    phone = data_id.replace("phone:", "").strip()
        except Exception:
            pass

        # Phone fallback via aria-label
        if not phone:
            try:
                phone_aria = page.locator('[aria-label*="Phone"]')
                if await phone_aria.count() > 0:
                    label = await phone_aria.first.get_attribute('aria-label', timeout=2000)
                    if label:
                        phone = label.split(":")[-1].strip()
            except Exception:
                pass

        # Address
        address = ""
        try:
            addr_button = page.locator('button[data-item-id="address"]')
            if await addr_button.count() > 0:
                address = await addr_button.first.inner_text(timeout=2000)
                address = address.replace('\ue0c8', '').strip()
        except Exception:
            pass

        return {
            "name":     name,
            "category": category,
            "website":  website,
            "phone":    phone,
            "address":  address,
            "map_url":  link,
        }
    except Exception as e:
        print(f"      ⚠️  Could not extract details from {link}: {e}")
        return None


from agents.utils import is_whatsapp_ready

def _meets_constraints(lead: dict, constraints: dict) -> bool:
    """Evaluates if a lead satisfies the semantic mission constraints."""
    if not constraints:
        return True
    
    # Website constraints
    website_status = constraints.get("website", "optional")
    has_website = bool(lead.get("website"))
    
    if website_status == "forbidden" and has_website:
        return False
    if website_status == "required" and not has_website:
        return False
        
    # Geographic location constraint (REMOVED)
    # Google Maps ya filtra por ubicación geográficamente. Hacer una comprobación 
    # estricta del string descartaba leads válidos que usaban el nombre de su barrio 
    # (ej. "Santurce" en lugar de "San Juan"). Por tanto, confiamos en el algoritmo de Google.
            
    # Phone / WhatsApp constraints
    phone_status = constraints.get("phone", "optional")
    has_phone = bool(lead.get("phone"))
    is_whatsapp = is_whatsapp_ready(lead.get("phone", ""))
    
    if phone_status == "required" and not has_phone:
        return False
    if phone_status == "whatsapp_only" and not is_whatsapp:
        return False
        
    return True


async def extract_leads(mission_data: dict, limit: int = 10, skip_existing: bool = True, headless: bool = False, resume: bool = True):
    """
    Main entry point. Accepts a mission_data dict containing queries and geographic intelligence,
    spoofs the browser location, and scrapes leads for each query using parallel tab extraction.
    """
    queries = mission_data.get("queries", [])
    latitude = mission_data.get("latitude", 0.0)
    longitude = mission_data.get("longitude", 0.0)
    locale = mission_data.get("locale", "en-US")
    timezone_id = mission_data.get("timezoneId", "America/New_York")
    constraints = mission_data.get("constraints", {})
    
    # Inject target_location into constraints for semantic filtering
    if "target_location" in mission_data:
        constraints["target_location"] = mission_data["target_location"]

    import os
    import glob
    import csv
    import json
    import shutil

    all_leads: list[dict] = []
    historical_seen_keys: set[str] = set()
    local_seen_keys: set[str] = set()

    results_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "results")
    os.makedirs(results_dir, exist_ok=True)
    
    safe_goal = mission_data.get("safe_goal", "default")
    
    raw_targets_path = os.path.join(results_dir, f"raw_targets_{safe_goal}.csv")
    failed_targets_path = os.path.join(results_dir, f"failed_targets_{safe_goal}.csv")
    clean_leads_path = os.path.join(results_dir, f"clean_leads_pre_ia_{safe_goal}.csv")
    deduped_out_path = os.path.join(results_dir, f"deduped_out_{safe_goal}.csv")
    summary_path = os.path.join(results_dir, f"dedupe_summary_{safe_goal}.json")

    # MIGRATION: Auto-migrate generic files from older runs to the scoped namespace
    generic_raw = os.path.join(results_dir, "raw_targets.csv")
    if os.path.exists(generic_raw) and not os.path.exists(raw_targets_path):
        try:
            shutil.move(generic_raw, raw_targets_path)
            for old, new in [
                ("failed_targets.csv", failed_targets_path),
                ("clean_leads_pre_ia.csv", clean_leads_path),
                ("deduped_out.csv", deduped_out_path),
                ("dedupe_summary.json", summary_path)
            ]:
                old_p = os.path.join(results_dir, old)
                if os.path.exists(old_p): shutil.move(old_p, new)
        except Exception as e:
            print(f"⚠️ Migration warning: {e}")

    # --- NEURAL MEMORY (Historical) ---
    try:
        if os.path.exists(results_dir):
            for csv_file in glob.glob(os.path.join(results_dir, "*.csv")):
                # Do not count the raw_targets or failed as memory
                if "raw_targets" in csv_file or "failed_targets" in csv_file or "deduped" in csv_file:
                    continue
                with open(csv_file, mode='r', encoding='utf-8-sig', errors='ignore') as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        keys = _generate_dedupe_keys(row)
                        historical_seen_keys.update(keys)
        msg = f"🧠 Neural Memory Loaded: {len(historical_seen_keys)} unique business signatures memorized from past campaigns."
        print(msg)
        yield msg
    except Exception as e:
        print(f"⚠️ Neural Memory warning: Could not load historical data: {e}")

    all_links: list[str] = []
    seen_links: set[str] = set()

    # --- RESUME MODE ---
    if resume and os.path.exists(raw_targets_path):
        yield "📂 Resume Mode: Detecting existing raw_targets.csv..."
        try:
            with open(raw_targets_path, "r", encoding="utf-8") as f:
                reader = csv.reader(f)
                header = next(reader, None)
                for row in reader:
                    if row and row[0].startswith("http"):
                        all_links.append(row[0].strip())
                
                # MATHEMATICAL DEDUPLICATION: Remove exact duplicate URLs instantly
                # Google Maps adds dynamic /data= tracking, so we normalize the base URL
                original_count = len(all_links)
                unique_links_dict = {}
                for link in all_links:
                    # e.g. https://www.google.com/maps/place/Clinica+X/data=123?hl=es -> https://www.google.com/maps/place/Clinica+X
                    base_url = link.split('/data=')[0].split('?')[0].strip()
                    if base_url not in unique_links_dict:
                        unique_links_dict[base_url] = link
                
                all_links = list(unique_links_dict.values())
                purged = original_count - len(all_links)
                
            yield f"   ✅ Loaded {len(all_links)} unique targets directly from file (Purged {purged} duplicates matemáticamente). Skipping Google Maps search phase."
        except Exception as e:
            yield f"   ⚠️ Could not read raw_targets.csv: {e}. Will scrape from scratch."
            all_links = []

    if not all_links and not queries:
        yield []
        return

    # Helper function to save progress
    def save_checkpoint(deduped_out, dedupe_summary):
        try:
            if deduped_out:
                keys_out = ["name", "category", "website", "phone", "address", "map_url", "dedupe_reason", "dedupe_key_used", "duplicate_of"]
                with open(deduped_out_path, "w", encoding="utf-8-sig") as f:
                    writer = csv.DictWriter(f, fieldnames=keys_out, extrasaction="ignore")
                    writer.writeheader()
                    writer.writerows(deduped_out)
            if all_leads:
                keys_clean = ["name", "category", "website", "phone", "address", "map_url"]
                with open(clean_leads_path, "w", encoding="utf-8-sig") as f:
                    writer = csv.DictWriter(f, fieldnames=keys_clean, extrasaction="ignore")
                    writer.writeheader()
                    writer.writerows(all_leads)
            with open(summary_path, "w", encoding="utf-8") as f:
                json.dump(dedupe_summary, f, indent=2)
        except Exception as e:
            print(f"⚠️ Checkpoint save failed: {e}")

    yield "🚀 Launching stealth browser engine (this takes a few seconds)..."

    async with async_playwright() as p:
        
        async def launch_stealth():
            b = await p.chromium.launch(
                headless=headless,
                args=[
                    '--disable-blink-features=AutomationControlled',
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-gpu',
                ]
            )
            c_args = {
                'viewport': {'width': 1280, 'height': 800},
                'user_agent': (
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/124.0.0.0 Safari/124.0.0.0'
                )
            }
            if latitude and longitude:
                c_args['geolocation'] = {'latitude': latitude, 'longitude': longitude}
                c_args['permissions'] = ['geolocation']
                c_args['locale'] = locale
                c_args['timezone_id'] = timezone_id
                
            c = await b.new_context(**c_args)
            stealth = Stealth()
            await stealth.apply_stealth_async(c)
            return b, c

        browser, context = await launch_stealth()

        # ── PHASE 1: Collect all place URLs across all queries ──────────────
        if not all_links:
            multiplier = 3 if constraints.get("website") == "forbidden" else 1.5
            links_per_query = max(int((limit // len(queries) + 3) * multiplier), 10)
            page = await context.new_page()
            
            for q_num, query in enumerate(queries):
                if len(all_links) >= limit * 3:
                    break

                yield f"🔎 Querying {q_num + 1}/{len(queries)} — '{query}'"
                try:
                    search_url = f"https://www.google.com/maps/search/{query.replace(' ', '+')}"
                    yield f"   🛰️ Navigating to search results..."
                    await page.goto(search_url, timeout=45000, wait_until="domcontentloaded")

                    if q_num == 0:
                        yield "   🛡️ Handling consent protocols..."
                        await _dismiss_cookie_banner(page)

                    yield "   ⏳ Extracting neural signals..."
                    try:
                        await page.wait_for_selector('div[role="feed"], div[aria-label^="Results for"], h1', timeout=12000)
                    except: pass

                    if "/maps/place/" in page.url:
                        yield "   📍 Single target identified."
                        link = page.url
                        if link not in seen_links:
                            seen_links.add(link)
                            all_links.append(link)
                        continue

                    feed_selector = 'div[role="feed"]'
                    if not await page.locator(feed_selector).is_visible():
                        if await page.locator('div[aria-label^="Results for"]').is_visible():
                            feed_selector = 'div[aria-label^="Results for"]'
                        elif await page.locator('div[aria-label^="Resultados de"]').is_visible():
                            feed_selector = 'div[aria-label^="Resultados de"]'
                        elif await page.locator('.m6QErb[aria-label]').first.is_visible():
                            feed_selector = '.m6QErb[aria-label]'

                    scroll_attempts = 0
                    max_scrolls = 20 if constraints.get("website") == "forbidden" else 12

                    while len([l for l in all_links]) < links_per_query * (q_num + 1) and scroll_attempts < max_scrolls:
                        if await page.locator(feed_selector).is_visible():
                            await page.hover(feed_selector)
                            await page.mouse.wheel(0, 4000)
                            await asyncio.sleep(0.5)

                        locator = page.locator('a[href*="/maps/place/"]')
                        count = await locator.count()
                        for i in range(count):
                            href = await locator.nth(i).get_attribute("href")
                            if href and href not in seen_links:
                                seen_links.add(href)
                                all_links.append(href)

                        scroll_attempts += 1

                    yield f"   📍 {len(all_links)} total targets collected so far."

                except Exception as e:
                    yield f"   ❌ Signal corruption on query '{query}': {e}"
                    continue
            
            try: await page.close()
            except: pass

            # Save raw targets
            try:
                with open(raw_targets_path, "w", encoding="utf-8") as f:
                    f.write("url\n")
                    for link in all_links:
                        f.write(f"{link}\n")
            except: pass

        # ── PHASE 2: Extract details with strict error handling & retries ──────────────
        # Increased to 5 since we now have robust tab closing and it speeds up mass-scraping without freezing Chromium.
        BATCH_SIZE = 5
        RESTART_EVERY = 1000
        
        # If resume=True, filter out leads already processed in clean_leads_pre_ia.csv
        if resume and os.path.exists(clean_leads_path):
            try:
                with open(clean_leads_path, "r", encoding="utf-8-sig") as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        keys = _generate_dedupe_keys(row)
                        local_seen_keys.update(keys)
                        all_leads.append(row)
                yield f"   ✅ Resumed {len(all_leads)} leads already extracted locally."
            except Exception as e:
                yield f"   ⚠️ Could not read existing clean leads: {e}"

        # Build final list to process
        links_to_process = []
        for l in all_links:
            # Check if historical memory already knows this EXACT url (if we're skipping existing)
            if skip_existing and is_already_known(l):
                continue
            
            # Check if local run already saw it (from the clean_leads_pre_ia.csv we just loaded!)
            url_key = f"url:{l.split('/data=')[0].split('?')[0].strip()}"
            if url_key in local_seen_keys:
                continue
            
            links_to_process.append(l)
            
        yield f"🚀 Processing {len(links_to_process)} targets in parallel batches of {BATCH_SIZE}..."

        # ── PRE-FLIGHT: Ensure Consent Cookies are set for the context ──
        # If we skipped Phase 1, the context has no cookies and Google will block every tab with a consent wall!
        try:
            yield "   🛡️ Pre-flight check: Handshaking with Google to bypass consent walls..."
            pre_page = await context.new_page()
            # Go to Google Search instead of Maps! It loads instantly and sets the exact same domain cookies.
            await pre_page.goto("https://www.google.com/", timeout=15000, wait_until="domcontentloaded")
            await _dismiss_cookie_banner(pre_page)
            await pre_page.close()
            yield "   ✅ Handshake complete. Engaging hyperdrive."
        except Exception as e:
            pass

        deduped_out = []
        dedupe_summary = {
            "processed": 0,
            "success": len(all_leads),
            "failed": 0,
            "skipped_constraints": 0,
            "duplicates": 0,
            "no_name": 0,
            "keys_used": {}
        }
        failed_targets = []

        async def extract_with_retry(link: str, ctx) -> tuple[str, tuple[Optional[dict], Optional[str]]]:
            """Returns (link, (lead_dict, error_string)) after up to 3 retries"""
            max_retries = 3
            last_error = None
            for attempt in range(max_retries):
                tab = None
                try:
                    tab = await ctx.new_page()
                    res = await _extract_place_details(tab, link)
                    await tab.close()
                    if res is None:
                        raise Exception("Place details returned None (Timeout or Blocked)")
                    return link, (res, None)
                except Exception as e:
                    last_error = f"{type(e).__name__}: {str(e)}"
                    print(f"      ⚠️  Attempt {attempt+1}/{max_retries} failed for {link}: {last_error}")
                    if tab:
                        try: await tab.close()
                        except: pass
                    await asyncio.sleep(1.5)
            return link, (None, last_error)

        # Initialize failed targets CSV header
        if not os.path.exists(failed_targets_path):
            with open(failed_targets_path, "w", encoding="utf-8-sig") as f:
                f.write("url,error\n")

        processed_since_restart = 0
        total_processed_phase2 = 0

        for batch_start in range(0, len(links_to_process), BATCH_SIZE):
            if len(all_leads) >= limit:
                break

            # --- Browser Auto-Restart Mechanism ---
            if processed_since_restart >= RESTART_EVERY:
                yield f"   🔄 Memory flush: Restarting stealth browser to prevent OOM crash..."
                try:
                    await asyncio.wait_for(context.close(), timeout=3.0)
                except: pass
                try:
                    await asyncio.wait_for(browser.close(), timeout=3.0)
                except: pass
                
                await asyncio.sleep(2)
                try:
                    browser, context = await launch_stealth()
                    # CRITICAL: We must dismiss the cookie banner again since this is a fresh context!
                    yield "   🛡️ Re-applying pre-flight cookie handshake for new browser..."
                    pre_page = await context.new_page()
                    await pre_page.goto("https://www.google.com/", timeout=15000, wait_until="domcontentloaded")
                    await _dismiss_cookie_banner(pre_page)
                    await pre_page.close()
                except Exception as e:
                    yield f"   ⚠️ Failed to launch new browser: {e}. Retrying..."
                    await asyncio.sleep(2)
                    browser, context = await launch_stealth()
                    
                processed_since_restart = 0

            batch = links_to_process[batch_start: batch_start + BATCH_SIZE]
            
            # Execute batch concurrently and wait with a hard timeout to prevent deadlocks
            tasks = [asyncio.create_task(extract_with_retry(link, context)) for link in batch]
            
            done, pending = await asyncio.wait(tasks, timeout=25.0)
            
            if pending:
                yield f"      ❌ Batch Hard Timeout! Playwright froze on {len(pending)} tasks. Cancelling zombies..."
                for p in pending:
                    p.cancel()
                    failed_targets.append({"url": "unknown", "error": "TaskCrash: Hard Timeout (Playwright froze)"})
                    dedupe_summary["failed"] += 1
            
            for completed_task in done:
                try:
                    link, res_tuple = completed_task.result()
                except Exception as e:
                    # Task crashed completely
                    error_msg = f"TaskCrash: {type(e).__name__}: {str(e)}"
                    failed_targets.append({"url": "unknown", "error": error_msg})
                    dedupe_summary["failed"] += 1
                    yield f"      ❌ Fatal extraction task crash: {error_msg}"
                    continue

                total_processed_phase2 += 1
                processed_since_restart += 1
                dedupe_summary["processed"] += 1
                
                lead, err = res_tuple
                
                if err is not None or lead is None:
                    # Failed after 3 retries
                    failed_targets.append({"url": link, "error": err or "Returned None"})
                    dedupe_summary["failed"] += 1
                    yield f"      ❌ Failed to extract: {link.split('?')[0].split('/')[-1][:20]}..."
                    continue

                # Validation
                name = lead.get("name", "Unknown")
                garbage_names = ["Unknown", "Antes de ir a Google", "Before you continue", "Google Maps", "Google"]
                if any(g.lower() in name.lower() for g in garbage_names) or len(name) < 2:
                    deduped_out.append({**lead, "dedupe_reason": f"Invalid Name: {name}", "dedupe_key_used": "N/A", "duplicate_of": "N/A"})
                    dedupe_summary["no_name"] += 1
                    continue
                    
                keys = _generate_dedupe_keys(lead)
                
                # Check local duplicates
                duplicate_key = next((k for k in keys if k in local_seen_keys), None)
                if duplicate_key:
                    deduped_out.append({**lead, "dedupe_reason": "Duplicado Local", "dedupe_key_used": duplicate_key, "duplicate_of": "N/A"})
                    dedupe_summary["duplicates"] += 1
                    prefix = duplicate_key.split(':')[0]
                    dedupe_summary["keys_used"][prefix] = dedupe_summary["keys_used"].get(prefix, 0) + 1
                    yield f"      ♻️ Duplicado Local descartado: {name}"
                    continue
                    
                # Check historical duplicates
                if skip_existing:
                    historical_key = next((k for k in keys if k in historical_seen_keys), None)
                    if historical_key:
                        deduped_out.append({**lead, "dedupe_reason": "Duplicado Histórico", "dedupe_key_used": historical_key, "duplicate_of": "N/A"})
                        dedupe_summary["duplicates"] += 1
                        prefix = historical_key.split(':')[0]
                        dedupe_summary["keys_used"][prefix] = dedupe_summary["keys_used"].get(prefix, 0) + 1
                        yield f"      ♻️ Duplicado Histórico descartado: {name}"
                        continue
                
                if _meets_constraints(lead, constraints):
                    local_seen_keys.update(keys)
                    all_leads.append(lead)
                    dedupe_summary["success"] = len(all_leads)
                    yield f"      ✅ Lead Decoded: {name}"
                else:
                    reason = "No website" if not lead.get("website") else "Has website"
                    deduped_out.append({**lead, "dedupe_reason": f"Constraint Failed: {reason}", "dedupe_key_used": "N/A", "duplicate_of": "N/A"})
                    dedupe_summary["skipped_constraints"] += 1
                    yield f"      ⏭️  Skipping '{name}' ({reason})"

            # Append new failed targets to CSV instantly
            if failed_targets:
                try:
                    with open(failed_targets_path, "a", encoding="utf-8-sig") as f:
                        writer = csv.DictWriter(f, fieldnames=["url", "error"])
                        writer.writerows(failed_targets)
                    failed_targets = [] # clear list after append
                except: pass

            # Periodic Checkpoint (every ~100 leads processed)
            if total_processed_phase2 > 0 and total_processed_phase2 % 100 < BATCH_SIZE:
                save_checkpoint(deduped_out, dedupe_summary)
                yield f"   💾 Persistent Checkpoint saved (Processed: {total_processed_phase2}, Success: {len(all_leads)})"

        # Final save
        save_checkpoint(deduped_out, dedupe_summary)

        try:
            await context.close()
            await browser.close()
        except: pass

    yield all_leads[:limit]

